services:
  db:
    image: postgres:16
    container_name: lab-05-pg
    ports:
      - "55437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lab
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped